#!/bin/bash

n=4
# scale 1/50 ; origin (3,0)
# 4 : [-50,100], [-20,20]
# 5 : [-82,144], [-35,35]
# 6 : [-100,174], [-43,43]
# ∞ : [-150,250], [-73,73]

ls=$(seq 0 4 400)
lt=$(seq -73 4 73)
./parallel --max-procs 50% --ungroup python3 python/deform.py  ::: $n ::: ${ls} ::: ${lt} ::: 0 ::: 0 ::: 0

ls=$(seq -150 2 5)
lt=$(seq -5 2 73)
./parallel --max-procs 50% --ungroup python3 python/deform.py  ::: $n ::: ${ls} ::: ${lt} ::: 0 ::: 0 ::: 0

ls=$(seq -150 4 5)
lt=$(seq -73 4 -5)
./parallel --max-procs 50% --ungroup python3 python/deform.py  ::: $n ::: ${ls} ::: ${lt} ::: 0 ::: 0 ::: 0

ls=$(seq -150 1 0)
./parallel --max-procs 50% --ungroup python3 python/deform.py  ::: $n ::: ${ls} ::: 0 ::: 1 ::: 0 ::: 0

ls=$(seq -150 1 400)
./parallel --max-procs 50% --ungroup python3 python/deform.py  ::: $n ::: ${ls} ::: 0 ::: 0 ::: 1 ::: 0

ls=$(seq -5 1 5)
lt=$(seq -5 1 5)
./parallel --max-procs 50% --ungroup python3 python/deform.py  ::: $n ::: ${ls} ::: ${lt} ::: 0 ::: 0 ::: 1
