#!/bin/bash

source ../.venv/bin/activate
python --version

n=4
# scale 1/50 ; origin (3,0)
# 4 : [-50,100], [-20,20]
# 5 : [-82,144], [-35,35]
# 6 : [-100,174], [-43,43]
# ∞ : [-150,400], [-73,73]

ls=$(seq -50 3 100)
lt=$(seq -20 3 20)
parallel --max-procs 75% --ungroup python python/deform.py  ::: $n ::: ${ls} ::: ${lt} ::: 0 ::: 0 ::: 0

ls=$(seq -50 1 1)
parallel --max-procs 75% --ungroup python python/deform.py  ::: $n ::: ${ls} ::: 0 ::: 1 ::: 0 ::: 0

ls=$(seq -50 1 100)
parallel --max-procs 75% --ungroup python python/deform.py  ::: $n ::: ${ls} ::: 0 ::: 0 ::: 1 ::: 0

ls=$(seq -3 1 3)
lt=$(seq -3 1 3)
parallel --max-procs 75% --ungroup python python/deform.py  ::: $n ::: ${ls} ::: ${lt} ::: 0 ::: 0 ::: 1
